# Docker with SQL MySQL
services:
  db:
   image: mysql:8.3
   container_name: lab4-mysql
   ports:
     - "3307:3306"
   environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'daynor.tito.mysql'
   restart: unless-stopped
   volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init-script.sql:/docker-entrypoint-initdb.d/databasemodel.sql
  
volumes:
  mysql_data: